### ISSUE TITLE
good_template_c++

### ISSUE THREAD

**Issue by mrhagrawal** [mrhagrawal/competitive_programming_resources#1]
A good template for coders to use during competitive coding.

**Comment by Abhicoder03** [comment]
I want to work on this. So I have to write documentation for good templates in c++?

**Comment by mrhagrawal** [comment]
> I want to work on this. So I have to write documentation for good templates in c++?

That will be great if you can write documentation for making a good template.

**Comment by Abhicoder03** [comment]
Sure. Could you assign this to me.

**Comment by Abhicoder03** [comment]
if you could review my work it would be great.

**Comment by mrhagrawal** [comment]
> if you could review my work it would be great.

Sure will do it in some time. 
Till then, Happy Learning!
